name: CI/CD pipline
on:
 push:
   branches: ["main"]
 pull_request:
   branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test with the dotnet CLI
      run: dotnet test

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file Items/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/items:latest
    - name: Log in to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push tag to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/items:latest
 
